AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Contact Form API Backend

Resources:
  ContactFormApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: ContactFormApi
      StageName: Prod
      Cors:
        AllowMethods: "'OPTIONS,POST'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"

  ContactFormFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.12
      CodeUri: contact_form/
      Handler: app.lambda_handler
      Events:
        SubmitContactForm:
          Type: Api
          Properties:
            Path: /contact
            Method: POST
            RestApiId: !Ref ContactFormApi
      Policies:
        - DynamoDBCrudPolicy:
            TableName: ContactFormMessages

  ContactFormTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ContactFormMessages
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST

Outputs:
  ApiEndpoint:
    Description: API Gateway endpoint URL for contact form
    Value: !Sub "https://${ContactFormApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/contact"